@ClockCalculatorApi_HostAddress = http://localhost:5276
@hours = 9
@minutes = 45

GET {{ClockCalculatorApi_HostAddress}}/api/calculatetimeangle?hours={{hours}}&minutes={{minutes}}
Accept: application/json

###

GET {{ClockCalculatorApi_HostAddress}}/api/calculatetimeangle/{{hours}}%3A{{minutes}}